### ISSUE TITLE
Extra actions buttom in raid gone

### ISSUE THREAD

**Issue by Boniewow** [fafaraway/andromeda#104] opened 2021-07-30 09:11 UTC
Did the boss Eye of the jailer. First time when you use the change the button was there sec time is was gone, Ofc i died :=)) Even when it was working it is wery small any way to make it bigger ? it is kind of important in raid!

**Comment by fafaraway** [comment] 2021-08-06 14:43
Did heroic Eye of the Jailer this week, extra action button works fine.
Please disable other addons to confirm whether the problem is caused by FreeUI.

**Comment by Boniewow** [comment] 2021-08-09 09:02
I realy hade no addon except weakauras and bigwigs, details.

**Comment by fafaraway** [comment] 2021-08-09 17:32
bind it with a shortcut key, there is no need to manually click the button

**Comment by Boniewow** [comment] 2021-08-10 07:02
Yeh already using it. the problem it is a same icon as on other
dungeon-quest boss fight and you cant se so easy when it is ready to use.
just wanted to report the bug :=)

**Comment by fafaraway** [comment] 2021-08-15 05:38
Did heroic Eye of the Jailer again this weekend and confirmed that the extra action button is working normally.
Close this issue for now unless you find more relevant clues ;)

**Closed as completed by fafaraway** 2021-08-15 05:38 UTC
